name: core
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  equatable: ^1.1.1
  rxdart: ^0.24.0
  dartz: ^0.8.9

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
